/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: hst.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _HST_H_
#define _HST_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef nsc__ns
#define nsc__ns 1217925993
#define nsc__ns_id "http://skku.com/iot/example/ietf-i2nsf-capability-interface"
#define nsc__ns_uri "http://skku.com/iot/example/ietf-i2nsf-capability-interface"
#endif

#define nsc_rule_id 227507396
#define nsc_policy 1919655803
#define nsc_pkt_sec_cond_ipv4_src_addr 329030715
#define nsc_apply_profile_action 381175434
#define nsc_action 571883887
#define nsc_syn_flood 347431706
#define nsc_dpi 272899794
#define nsc_condition 1305639641
#define nsc_pkt_sec_cond_ipv4_dest_addr 1270618179
#define nsc_packet_sec_condition 1013115873
#define nsc_rules 1786933435
#define nsc_egress_action 1482392572
#define nsc_start_time 84038180
#define nsc_schedule 1642863984
#define nsc_permit 1901628419
#define nsc_packet_sec_ipv4 41090496
#define nsc_end_time 1935053864
#define nsc_generic_context_condition 1778205818
#define nsc_deny 1028777810
#define nsc_action_type 731500332
#define nsc_signal 990641426
#define nsc_mirror 1704418088
#define nsc_rule_name 1230353606
#define nsc_encapsulate 178977950
#define nsc_ingress_action 688643849
#define nsc__callpointid_hcp "hcp"

#ifdef __cplusplus
}
#endif

#endif
