/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: hst.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _HST_H_
#define _HST_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef dpi__ns
#define dpi__ns 1217925993
#define dpi__ns_id "http://skku.com/iot/example/ietf-i2nsf-capability-interface"
#define dpi__ns_uri "http://skku.com/iot/example/ietf-i2nsf-capability-interface"
#endif

#define dpi_voip_volte_rule 1943393205
#define dpi_rule_id 227507396
#define dpi_policy 1919655803
#define dpi_action 571883887
#define dpi_event 1332659655
#define dpi_condition 1305639641
#define dpi_permit 1901628419
#define dpi_called_voip 375321881
#define dpi_sip_uri 725539211
#define dpi_deny 1028777810
#define dpi_action_type 731500332
#define dpi_sip_user_agent 583417013
#define dpi_mirror 1704418088
#define dpi_called_volte 1593210203
#define dpi_rule_name 1230353606
#define dpi_ingress_action 688643849
#define dpi__callpointid_hcp "hcp"

#ifdef __cplusplus
}
#endif

#endif
