#~/bin/sh

if [ "$#" -lt 2 ]; then
    echo "Usage: ./sendFlowScript.sh [PUT or DELETE] [IP Address with port of controller]"
    exit 1
fi

curl -X "$1" -H "Content-Type: application/xml" "http://$2/restconf/config/opendaylight-inventory:nodes/node/openflow:2/table/0/flow/Test01" -v -u admin:admin -d '<?xml version="1.0" encoding="UTF-8" standalone="no"?><flow xmlns="urn:opendaylight:flow:inventory"><strict>false</strict><flow-name>Test01</flow-name><id>Test01</id><cookie_mask>255</cookie_mask><cookie>103</cookie><table_id>0</table_id><priority>100</priority><hard-timeout>1200</hard-timeout><idle-timeout>3400</idle-timeout><installHw>false</installHw><instructions><instruction><order>0</order><apply-actions><action><order>0</order><output-action><output-node-connector>openflow:2:1</output-node-connector><max-length>65535</max-length></output-action></action></apply-actions></instruction></instructions><match><ethernet-match><ethernet-type><type>2048</type></ethernet-type></ethernet-match><ip-match><ip-protocol>145</ip-protocol></ip-match><in-port>openflow:2:3</in-port></match></flow>'


curl -X "$1" -H "Content-Type: application/xml" "http://$2/restconf/config/opendaylight-inventory:nodes/node/openflow:2/table/0/flow/Test02" -v -u admin:admin -d '<?xml version="1.0" encoding="UTF-8" standalone="no"?><flow xmlns="urn:opendaylight:flow:inventory"><strict>false</strict><flow-name>Test02</flow-name><id>Test02</id><cookie_mask>255</cookie_mask><cookie>103</cookie><table_id>0</table_id><priority>100</priority><hard-timeout>1200</hard-timeout><idle-timeout>3400</idle-timeout><installHw>false</installHw><instructions><instruction><order>0</order><apply-actions><action><order>0</order><output-action><output-node-connector>openflow:2:1</output-node-connector><max-length>65535</max-length></output-action></action></apply-actions></instruction></instructions><match><ethernet-match><ethernet-type><type>2048</type></ethernet-type></ethernet-match><ip-match><ip-protocol>145</ip-protocol></ip-match><in-port>openflow:2:4</in-port></match></flow>'

#curl -X "$1" -H "Content-Type: application/xml" "http://192.168.30.131:8181/restconf/config/opendaylight-inventory:nodes/node/openflow:3/table/0/flow/Test03" -v -u admin:admin -d '<?xml version="1.0" encoding="UTF-8" standalone="no"?><flow xmlns="urn:opendaylight:flow:inventory"><strict>false</strict><flow-name>Test03</flow-name><id>Test03</id><cookie_mask>255</cookie_mask><cookie>103</cookie><table_id>0</table_id><priority>100</priority><hard-timeout>1200</hard-timeout><idle-timeout>3400</idle-timeout><installHw>false</installHw><instructions><instruction><order>0</order><apply-actions><action><order>0</order><output-action><output-node-connector>openflow:3:3</output-node-connector><max-length>65535</max-length></output-action></action></apply-actions></instruction></instructions><match><in-port>openflow:3:1</in-port><ip-match><ip-protocol>145</ip-protocol></ip-match></match></flow>'

#curl -X "$1" -H "Content-Type: application/xml" "http://192.168.30.131:8181/restconf/config/opendaylight-inventory:nodes/node/openflow:3/table/0/flow/Test04" -v -u admin:admin -d '<?xml version="1.0" encoding="UTF-8" standalone="no"?><flow xmlns="urn:opendaylight:flow:inventory"><strict>false</strict><flow-name>Test04</flow-name><id>Test04</id><cookie_mask>255</cookie_mask><cookie>103</cookie><table_id>0</table_id><priority>100</priority><hard-timeout>1200</hard-timeout><idle-timeout>3400</idle-timeout><installHw>false</installHw><instructions><instruction><order>0</order><apply-actions><action><order>0</order><output-action><output-node-connector>openflow:3:3</output-node-connector><max-length>65535</max-length></output-action></action></apply-actions></instruction></instructions><match><in-port>openflow:3:2</in-port><ip-match><ip-protocol>145</ip-protocol></ip-match></match></flow>'

